modLoader = "javafml"
loaderVersion = "[36,)"

license = "All Rights Reserved"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId = "cnpcefaddon"
version = "${file.jarVersion}"
displayName = "CNPC-EpicFight-Addon"

#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="Goodbird"

description = '''
A compatibility bridge between CustomNPCs and EpicFight
'''

[[dependencies.cnpcefaddon]]
modId = "minecraft"
versionRange = "[1.18.2,1.19)"
mandatory = true
side = "BOTH"
ordering = "NONE"

[[dependencies.cnpcefaddon]]
modId = "forge"
versionRange = "[36,)"
mandatory = true
side = "BOTH"
ordering = "NONE"